---
galaxy_info:
  author: Kegan Holtzhausen
  company: Psimax Aerospace
  license: MIT
  min_ansible_version: 1.4

  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  categories:
  - system

dependencies: []